<?php
/**
 * User: execut
 * Date: 25.07.16
 * Time: 9:59
 */

namespace execut\actions\action\adapter;


use execut\actions\TestCase;
use yii\db\ActiveRecord;
use yii\db\IntegrityException;
use yii\helpers\Url;
use yii\web\Request;
use yii\web\Response;

class DeleteTest extends TestCase
{
    public function setUp():void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $_SERVER['HTTP_REFERER'] = 'test';
    }

    public function tearDown():void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
        $_SERVER['HTTP_REFERER'] = null;
    }

    public function testRun() {
        $this->markTestSkipped('Need repair');
        $action = new Delete();
        \yii::$app->layout = 'test';
        $action->isRedirect = false;
        $action->modelClass = DeleteTestModel::class;
        $action->setActionParams([
            'get' => [
                'id' => 1,
            ],
            'module' => 'testModule',
            'controller' => 'testController',
            'action' => 'testAction'
        ]);
        $action->setModelsFinder([
            'isCastParameters' => false,
        ]);

        $response = $action->run();

        $this->assertInstanceOf(Response::class, $response->content);
        $this->assertEquals('test', $response->content->getHeaders()->get('Location'));

        $model = $action->model;
        $this->assertTrue($model->isDeleteCalled);
        $this->assertEquals(1, $model->pk);

        $this->assertEquals([
            'kv-detail-success' => 'Record #' . $model->id . ' is successfully deleted',
        ], $response->flashes);
    }

    public function testRunWithRelationsError() {
        $action = new Delete();
        $model = new DeleteTestModel();
        $model->isThrowRelationErorrException = true;
        $action->setModel($model);
        $response = $action->run();

        $this->assertEquals([
            'kv-detail-warning' => 'Record #' . $model->id . ' cannot be deleted because it has associated entries that cannot be deleted. Error content: "test exception".',
        ], $response->flashes);
    }

    /**
     * @link https://github.com/execut/yii2-actions/issues/2
     */
    public function testDeleteExsitedRecordError() {
        $action = new Delete();
        $action->setModel(false);
        $response = $action->run();

        $this->assertEquals([
            'kv-detail-warning' => 'You are trying to delete an already deleted entry.',
        ], $response->flashes);
    }
}

class DeleteTestModel extends ActiveRecord {
    public $isDeleteCalled = false;
    public $isThrowRelationErorrException = false;
    public $pk = null;
    public $id = 1;
    public $primaryKey = 1;

    public static function primaryKey()
    {
        return 'id';
    }

    public static function find() {
        $model = new self;

        return $model;
    }

    public function andWhere($where) {
        $this->pk = $where['id'];
        return $this;
    }

    public function one() {
        return $this;
    }

    public function delete()
    {
        if ($this->isThrowRelationErorrException) {
            throw new IntegrityException('test exception');
        }

        return $this->isDeleteCalled = true;
    }

    public function __toString()
    {
        return 'deletedModel';
    }
}